name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend - Install
        run: cd backend && npm i
      - name: Frontend - Install
        run: cd frontend && npm i
      - name: Frontend - Build
        run: cd frontend && npm run build
